### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by tghelere** [tghelere/My-Fish-Funcs#1]
- [ ] Document all functions with comments
	- [ ] fishing.fish
	- [ ] ga..fish
	- [ ] gau.fish
	- [ ] gc.fish
	- [ ] gl.fish
	- [ ] gl+.fish
	- [ ] gs2.fish
	- [ ] gs2l.fish
	- [ ] gs2p.fish
	- [ ] gs2s.fish
	- [ ] gs.fish
	- [ ] saud.fish
	- [ ] saug.fish
	- [ ] x100.fish
	- [ ] x40.fish
	- [ ] x50.fish
	- [ ] x60.fish
	- [ ] x70.fish
	- [ ] x80.fish
	- [ ] x90.fish

- [ ] Create CONTRIBUTING.md

- [ ] Update README.md with instructions for creating new functions

- [ ] Test installation commands described in README.md

- [ ] Link in readme.md the official fish functions documentation for more information

- [ ] Update 'fishing' function and README.md to list only functions 'll' => 'll * .fish', hiding other files like README.md, CONTRIBUTING.md, LICENSE, etc.

## New features (Ideas)

- [ ] Create new branches that can be useful to specific users 
	* Ex: branch for debian_based_distros with useful commands like apt-update (saud)
	* Ex: branch projects so that the user can create the project functions (go to the x folder and build the project)
- [ ] Create scripts folder with shell scripts to execute in functions (ex: resize_swap.sh, clean_swap.sh, clone_and_build_x_project.sh)
